# Permalinks
permalink:        pretty

# Setup
title:            'micromagnetics'
tagline:          'theory and numerics'
description:      ''
url:              http://micromagnetics.org
baseurl:          '/'

author:
  name:           'Claas Abert'

paginate:         5
