# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'micromagnetics'
tagline:          'theory and numerics'
description:      ''
url:              http://micromagnetics.org
baseurl:          /

author:
  name:           'Claas Abert'

paginate:         5
